### ISSUE TITLE
Why is this a thing?

### ISSUE THREAD

**Issue by NathanW-05** [HausemasterIssue/VeteranHack-Decomp#1]
Why would decompile a client from like 2 years ago and upload it on github? It isn't even buildable

**Comment by HausemasterIssue** [comment]
archival purposes

**Comment by master7720** [comment]
> Why would decompile a client from like 2 years ago and upload it on github? It isn't even buildable

Probably cuz he was bored

**Comment by NathanW-05** [comment]
> archival purposes

It is already is a million archives, but ok

**Comment by master7720** [comment]
> > archival purposes
> 
> It is already is a million archives, but ok

your right but no one has posted the src before

**Comment by NathanW-05** [comment]
> > > archival purposes
> > 
> > 
> > It is already is a million archives, but ok
> 
> your right but no one has posted the src before

This isn't really source this is a decompilation, which no one has posted before because it is stupid. If someone wanted to look at the decompiled code they just decompile the jar themselves. It would actually make sense to post on github if it was buildable lol

**Comment by master7720** [comment]
...

**Comment by HausemasterIssue** [comment]
mc_field_27 is not fun to read
